name: CI/CD with Signing

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/myapp:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/myapp:latest

    - name: Install cosign
      run: |
        curl -LO https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
        chmod +x cosign-linux-amd64
        mv cosign-linux-amd64 /usr/local/bin/cosign

    - name: Sign Docker image
      run: cosign sign ghcr.io/${{ github.repository_owner }}/myapp:latest --key ${{ secrets.COSIGN_KEY }}

    - name: Verify Docker image
      run: cosign verify --key cosign.pub ghcr.io/${{ github.repository_owner }}/myapp:latest

