name: Container Signing

on:
  push:
    branches:
      - main

jobs:
  sign-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/myapp:latest .
          docker push ghcr.io/${{ github.repository }}/myapp:latest

      - name: Sign Docker image
        run: |
          cosign sign ghcr.io/${{ github.repository }}/myapp:latest
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
